variable "name_prefix" { type = string }
variable "service" { type = string }
variable "environment" { type = string }
variable "subnet_ids" { type = list(string) }
variable "app_security_group_id" { type = string }
variable "target_group_arn" { type = string }
variable "instance_profile_name" { type = string }
variable "instance_type" { type = string }
variable "desired_capacity" { type = number }
variable "min_size" { type = number }
variable "max_size" { type = number }
# variable "app_port" { type = number }
# variable "health_path" { type = string }
